import { InsurancePlan } from './types';

/**
 * Sample insurance plans for development and testing purposes.
 * These plans provide realistic data that can be used until real partnerships 
 * with insurance providers are established.
 */
export const samplePlans: InsurancePlan[] = [
  {
    id: 1,
    name: "Essential Cover",
    provider: "SecureTravel",
    basePrice: 45,
    medicalCoverage: 100000,
    tripCancellation: "Hasta $5,000",
    baggageProtection: 1500,
    emergencyEvacuation: 250000,
    adventureActivities: false,
    rentalCarCoverage: 0,
    rating: "4.2",
    reviews: 156,
    country: "colombia"
  },
  {
    id: 2,
    name: "Premium Protection",
    provider: "WorldWide Assurance",
    basePrice: 78,
    medicalCoverage: 250000,
    tripCancellation: "Hasta $10,000",
    baggageProtection: 3000,
    emergencyEvacuation: 500000,
    adventureActivities: true,
    rentalCarCoverage: 35000,
    rating: "4.7",
    reviews: 203,
    country: "colombia"
  },
  {
    id: 3,
    name: "Adventure Seeker",
    provider: "ExplorerShield",
    basePrice: 92,
    medicalCoverage: 200000,
    tripCancellation: "Hasta $7,500",
    baggageProtection: 2500,
    emergencyEvacuation: 400000,
    adventureActivities: true,
    rentalCarCoverage: 25000,
    rating: "4.5",
    reviews: 178,
    country: "colombia"
  },
  {
    id: 4,
    name: "Business Traveler",
    provider: "Corporate Shield",
    basePrice: 85,
    medicalCoverage: 300000,
    tripCancellation: "Hasta $15,000",
    baggageProtection: 5000,
    emergencyEvacuation: 350000,
    adventureActivities: false,
    rentalCarCoverage: 40000,
    rating: "4.6",
    reviews: 142,
    country: "colombia"
  },
  {
    id: 5,
    name: "Budget Friendly",
    provider: "EconoTravel",
    basePrice: 32,
    medicalCoverage: 50000,
    tripCancellation: "Hasta $2,500",
    baggageProtection: 1000,
    emergencyEvacuation: 100000,
    adventureActivities: false,
    rentalCarCoverage: 0,
    rating: "3.9",
    reviews: 214,
    country: "colombia"
  },
  {
    id: 6,
    name: "Family Plan",
    provider: "FamilyGuard",
    basePrice: 120,
    medicalCoverage: 350000,
    tripCancellation: "Hasta $20,000",
    baggageProtection: 7500,
    emergencyEvacuation: 600000,
    adventureActivities: true,
    rentalCarCoverage: 30000,
    rating: "4.8",
    reviews: 189,
    country: "colombia"
  },
  {
    id: 7,
    name: "Cobertura Básica",
    provider: "Seguro Viaje México",
    basePrice: 40,
    medicalCoverage: 80000,
    tripCancellation: "Hasta $4,000",
    baggageProtection: 1200,
    emergencyEvacuation: 200000,
    adventureActivities: false,
    rentalCarCoverage: 0,
    rating: "4.0",
    reviews: 123,
    country: "mexico"
  },
  {
    id: 8,
    name: "Protección Total",
    provider: "AztecaSeguro",
    basePrice: 85,
    medicalCoverage: 200000,
    tripCancellation: "Hasta $8,000",
    baggageProtection: 2500,
    emergencyEvacuation: 400000,
    adventureActivities: true,
    rentalCarCoverage: 30000,
    rating: "4.5",
    reviews: 167,
    country: "mexico"
  },
  {
    id: 9,
    name: "Plan Aventurero",
    provider: "Explora Seguro",
    basePrice: 95,
    medicalCoverage: 180000,
    tripCancellation: "Hasta $6,000",
    baggageProtection: 2000,
    emergencyEvacuation: 350000,
    adventureActivities: true,
    rentalCarCoverage: 20000,
    rating: "4.4",
    reviews: 156,
    country: "mexico"
  },
  {
    id: 10,
    name: "Global Traveler",
    provider: "International Care",
    basePrice: 110,
    medicalCoverage: 500000,
    tripCancellation: "Hasta $25,000",
    baggageProtection: 8000,
    emergencyEvacuation: 750000,
    adventureActivities: true,
    rentalCarCoverage: 50000,
    rating: "4.9",
    reviews: 234,
    country: "all"
  }
];