import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, SPACING, FONT_SIZES } from '../utils/theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerContent: {
    marginBottom: SPACING.md,
  },
  headerTitle: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: SPACING.xs,
  },
  headerSubtitle: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.white,
    opacity: 0.9,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: SPACING.md,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  tripDetailsCard: {
    marginVertical: SPACING.md,
    borderRadius: 15,
    elevation: 3,
  },
  weatherCard: {
    marginVertical: SPACING.md,
    borderRadius: 15,
    elevation: 3,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    marginBottom: SPACING.md,
    backgroundColor: COLORS.surface,
  },
  picker: {
    height: 50,
  },
  inputLabel: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  riskLevelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: SPACING.sm,
    padding: SPACING.md,
    borderRadius: 10,
    borderLeftWidth: 5,
  },
  riskLevelText: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    marginLeft: SPACING.sm,
  },
  riskLevelDescription: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
  },
  insuranceRecommendationCard: {
    marginTop: SPACING.md,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 10,
    padding: SPACING.md,
  },
  recommendationTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: SPACING.xs,
  },
  recommendationText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.text,
    lineHeight: 20,
  },
  ctaButton: {
    borderRadius: 10,
    marginTop: SPACING.md,
    marginBottom: SPACING.lg,
  },
  ctaButtonContent: {
    height: 50,
    justifyContent: 'center',
  },
  ctaButtonLabel: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 25,
    padding: 5,
    marginTop: SPACING.md,
    position: 'relative',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    zIndex: 1,
  },
  activeTab: {
    backgroundColor: 'transparent',
  },
  tabText: {
    marginLeft: 5,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  tabIndicator: {
    position: 'absolute',
    width: '50%',
    height: '100%',
    borderRadius: 20,
    backgroundColor: COLORS.white,
    top: 5,
    left: 5,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    zIndex: 0,
  },
  destinationCarouselContainer: {
    marginTop: SPACING.md,
    padding: SPACING.md,
  },
  carouselLabel: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    marginBottom: SPACING.sm,
    color: COLORS.text,
  },
  carouselContent: {
    paddingVertical: SPACING.sm,
  },
  destinationItem: {
    marginRight: SPACING.md,
    width: width / 3,
    height: width / 3,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  selectedDestinationItem: {
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  destinationImageContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.sm,
  },
  destinationName: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
  },
  destinationCountry: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  riskIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  destinationContainer: {
    marginVertical: SPACING.md,
  },
  destinationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.sm,
  },
  destinationTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  safetyScoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  safetyScoreLabel: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    marginRight: SPACING.sm,
  },
  safetyScore: {
    fontSize: FONT_SIZES.lg,
    fontWeight: 'bold',
  },
  progressContainer: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  disclaimerCard: {
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
    borderRadius: 15,
    backgroundColor: COLORS.white,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  disclaimerContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  disclaimerText: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.textSecondary,
    marginLeft: SPACING.sm,
    flex: 1,
    lineHeight: 18,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xl,
  },
  weatherDetailsContainer: {
    marginTop: SPACING.md,
  },
  safetyTipsContainer: {
    marginTop: SPACING.md,
  },
  safetyTipItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SPACING.md,
  },
  safetyTipNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SPACING.sm,
  },
  safetyTipNumberText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: FONT_SIZES.xs,
  },
  safetyTipContent: {
    flex: 1,
  },
  safetyTipTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 4,
  },
  safetyTipDescription: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  monthPickerContainer: {
    marginBottom: SPACING.md,
  },
  segmentedButtons: {
    marginBottom: SPACING.md,
  },
});